# Generated by Django 2.2.8 on 2020-02-03 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=200)),
                ('owners_id_number', models.IntegerField()),
                ('price_per_day', models.IntegerField()),
                ('Equipmemt_current_status', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='National_ID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Lands',
            fields=[
                ('Land_id', models.AutoField(primary_key=True, serialize=False)),
                ('land_size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('land_location', models.CharField(max_length=200)),
                ('Specifics', models.CharField(max_length=200)),
                ('image1', models.FileField(upload_to='')),
                ('image2', models.FileField(upload_to='')),
                ('Owners_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.User')),
            ],
        ),
    ]
