# Generated by Django 2.2.8 on 2020-02-05 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Smallscale', '0002_auto_20200203_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('National_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_number', models.IntegerField()),
                ('subcounty', models.CharField(choices=[('viola', 'Violas'), ('joan', 'Joans')], max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
