# Generated by Django 2.2.8 on 2020-02-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0003_auto_20200205_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='owners_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Profile'),
        ),
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Profile'),
        ),
    ]
