# Generated by Django 2.2.8 on 2020-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0004_auto_20200205_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='owners_id_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.IntegerField(),
        ),
    ]
