# Generated by Django 2.2.8 on 2020-02-05 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0006_equipment_equipment_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lands',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lands',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
