# Generated by Django 2.2.8 on 2020-02-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0008_auto_20200206_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='subcounty',
            field=models.CharField(blank=True, choices=[('viola', 'Violas'), ('joan', 'Joans')], max_length=200, null=True),
        ),
    ]
