# Generated by Django 2.2.8 on 2020-02-06 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0009_auto_20200206_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmers',
            name='subcounty',
            field=models.CharField(max_length=200),
        ),
    ]
