# Generated by Django 2.2.8 on 2020-02-08 10:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0010_auto_20200206_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
