# Generated by Django 2.2.8 on 2020-02-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0012_chatmessage_thread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lands',
            name='image1',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lands',
            name='image2',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
