# Generated by Django 2.2.8 on 2020-02-13 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0013_auto_20200213_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lands',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='lands',
            name='image2',
        ),
    ]
