# Generated by Django 2.2.8 on 2020-02-14 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0015_auto_20200214_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='lands',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
