# Generated by Django 2.2.8 on 2020-02-14 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0016_lands_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lands',
            name='land_size',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owners_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
        migrations.CreateModel(
            name='requestequip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('request_status', models.BooleanField(default=False)),
                ('equipment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.equipment')),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestequip_request_receiver', to='Smallscale.Farmers')),
                ('sender_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestequip_request_sender', to='Smallscale.Farmers')),
            ],
        ),
    ]
