# Generated by Django 2.2.8 on 2020-02-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0017_auto_20200214_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='veterinaries',
            fields=[
                ('Vet_Name', models.CharField(max_length=200)),
                ('ID_number', models.IntegerField(primary_key=True, serialize=False)),
                ('Email_address', models.EmailField(max_length=254)),
                ('Mobile_Number', models.IntegerField()),
                ('Specialization', models.CharField(max_length=200)),
                ('subcounty', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
