# Generated by Django 2.2.8 on 2020-02-16 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0018_veterinaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaries',
            name='subcounty',
            field=models.CharField(choices=[('AI', 'AINABKOI'), ('KP', 'KAPSERET'), ('KE', 'KESSES'), ('MO', 'MOIBEN'), ('SO', 'SOY'), ('TR', 'TURBO')], max_length=2),
        ),
    ]
