# Generated by Django 2.2.8 on 2020-02-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0019_auto_20200216_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veterinaries',
            name='location',
        ),
        migrations.AddField(
            model_name='veterinaries',
            name='ward',
            field=models.CharField(choices=[('AIN', 'AINABKOI'), ('KAP', 'KAPTAGAT'), ('KAPS', 'KAPSOYA'), ('KAPSE', 'SIMAT/KAPSERET'), ('KIPK', 'KIPKENYO'), ('MEG', 'MEGUN'), ('NER', 'NGERIA'), ('CHEP', 'CHEPTIRET/KIPMACHO'), ('RACE', 'RACECOURSE'), ('TUL', 'TULWET/CHUIYAT'), ('MEI', 'MEIBEKI'), ('KIMUMU', 'KIMUMU'), ('MOI', 'MOIBEN'), ('SER', 'SERGOIT'), ('TEM', 'TEMBELIO'), ('KAPKU', 'KAPKURES'), ('KIPSO', 'KIPSOMBA'), ('KUI', 'KUINET'), ('MOIB', 'MIOS BRIDGE'), ('SEG', 'SEGERO'), ('SOY', 'SOY'), ('ZIW', 'ZIWA'), ('HUR', 'HURUMA'), ('KAMA', 'KAMAGUT'), ('KIPLO', 'KIPLOMBE'), ('KAPSA', 'KAPSAOS'), ('NGE', 'NGENYILEL'), ('TAP', 'TAPSAGOI'), ('TAR', 'TARAKWA')], default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='veterinaries',
            name='subcounty',
            field=models.CharField(choices=[('AI', 'AINABKOI'), ('KP', 'KAPSERET'), ('KE', 'KESSES'), ('MO', 'MOIBEN'), ('SO', 'SOY'), ('TR', 'TURBO')], max_length=200),
        ),
    ]
