# Generated by Django 2.2.8 on 2020-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0021_veterinaries_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaries',
            name='Specialization',
            field=models.CharField(choices=[('POL', 'POULTRY'), ('FISH', 'FISHERIES'), ('ANIMMED', 'ANIMAL MEDICINE'), ('DIAGNOSIS', 'ANIMAL HEALTH DIAGNOSTICS'), ('WELFARE', 'ANIMAL WELFARE'), ('DENTIST', 'ANIMAL DENTISTRY'), ('EMERGENCY', 'VETERINARY EMERGENCY/INTENSIVE CARE'), ('NUTRITION', 'ANIMAL NUTRITION')], max_length=200),
        ),
    ]
