# Generated by Django 2.2.8 on 2020-02-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0022_auto_20200216_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='owners_id_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestequip',
            name='equipment_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestequip',
            name='receiver_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestequip',
            name='sender_ID',
            field=models.IntegerField(),
        ),
    ]
