# Generated by Django 2.2.8 on 2020-02-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0023_auto_20200217_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinaries',
            name='Specialization',
            field=models.CharField(choices=[('POULTRY', 'POULTRY'), ('FISHERIES', 'FISHERIES'), ('ANIMAL MEDICINE', 'ANIMAL MEDICINE'), ('ANIMAL HEALTH DIAGNOSTICS', 'ANIMAL HEALTH DIAGNOSTICS'), ('ANIMAL WELFARE', 'ANIMAL WELFARE'), ('ANIMAL DENTISTRY', 'ANIMAL DENTISTRY'), ('VETERINARY EMERGENCY/INTENSIVE CARE', 'VETERINARY EMERGENCY/INTENSIVE CARE'), ('ANIMAL NUTRITION', 'ANIMAL NUTRITION')], max_length=200),
        ),
        migrations.AlterField(
            model_name='veterinaries',
            name='subcounty',
            field=models.CharField(choices=[('AINABKOI', 'AINABKOI'), ('KAPSERET', 'KAPSERET'), ('KESSES', 'KESSES'), ('MOIBEN', 'MOIBEN'), ('SOY', 'SOY'), ('TURBO', 'TURBO')], max_length=200),
        ),
        migrations.AlterField(
            model_name='veterinaries',
            name='ward',
            field=models.CharField(choices=[('AINABKOI', 'AINABKOI'), ('KAPTAGAT', 'KAPTAGAT'), ('KAPSOYA', 'KAPSOYA'), ('SIMAT/KAPSERET', 'SIMAT/KAPSERET'), ('KIPKENYO', 'KIPKENYO'), ('MEGUN', 'MEGUN'), ('NGERIA', 'NGERIA'), ('CHEPTIRET/KIPMACHO', 'CHEPTIRET/KIPMACHO'), ('RACECOURSE', 'RACECOURSE'), ('TULWET/CHUIYAT', 'TULWET/CHUIYAT'), ('MEIBEKI', 'MEIBEKI'), ('KIMUMU', 'KIMUMU'), ('MOIBEN', 'MOIBEN'), ('SERGOIT', 'SERGOIT'), ('TEMBELIO', 'TEMBELIO'), ('KAPKURES', 'KAPKURES'), ('KIPSOMBA', 'KIPSOMBA'), ('KUINET', 'KUINET'), ('MIOS BRIDGE', 'MIOS BRIDGE'), ('SEGERO', 'SEGERO'), ('SOY', 'SOY'), ('ZIWA', 'ZIWA'), ('HURUMA', 'HURUMA'), ('KAMAGUT', 'KAMAGUT'), ('KIPLOMBE', 'KIPLOMBE'), ('KAPSAOS', 'KAPSAOS'), ('NGENYILEL', 'NGENYILEL'), ('TAPSAGOI', 'TAPSAGOI'), ('TARAKWA', 'TARAKWA')], max_length=200),
        ),
    ]
