# Generated by Django 2.2.8 on 2020-02-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0025_veterinaries_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='vetrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VeterinaryID_number', models.IntegerField()),
                ('FarmerID_number', models.IntegerField()),
                ('request_status', models.BooleanField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
