# Generated by Django 2.2.8 on 2020-02-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0026_vetrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetrequest',
            old_name='FarmerID_number',
            new_name='Farmer_ID_number',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='VeterinaryID_number',
            new_name='Veterinary_ID_number',
        ),
    ]
