# Generated by Django 2.2.8 on 2020-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0027_auto_20200217_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='landrequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('My_ID_number', models.IntegerField()),
                ('My_name', models.CharField(max_length=200)),
                ('Land_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_status', models.BooleanField(default=0)),
            ],
        ),
    ]
