# Generated by Django 2.2.8 on 2020-02-20 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0028_landrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
    ]
