# Generated by Django 2.2.8 on 2020-02-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0029_auto_20200220_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lands',
            name='Owners_id',
            field=models.IntegerField(),
        ),
    ]
