# Generated by Django 2.2.8 on 2020-02-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0032_auto_20200221_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lands',
            name='Owners_id',
        ),
        migrations.AddField(
            model_name='lands',
            name='My_ID_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
