# Generated by Django 2.2.8 on 2020-02-20 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0033_auto_20200221_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='lands',
            name='farmer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
            preserve_default=False,
        ),
    ]
