# Generated by Django 2.2.8 on 2020-02-21 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0034_lands_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lands',
            old_name='farmer',
            new_name='farmerID',
        ),
        migrations.RenameField(
            model_name='lands',
            old_name='Specifics',
            new_name='more_info',
        ),
        migrations.RenameField(
            model_name='lands',
            old_name='My_ID_number',
            new_name='nationalID_number',
        ),
        migrations.RenameField(
            model_name='lands',
            old_name='price',
            new_name='price_per_acre',
        ),
        migrations.RemoveField(
            model_name='lands',
            name='Land_id',
        ),
        migrations.AddField(
            model_name='lands',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
