# Generated by Django 3.0.3 on 2020-02-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0035_auto_20200221_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='lands',
            name='land_size',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
