# Generated by Django 3.0.3 on 2020-02-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0036_lands_land_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrequest',
            name='My_ID_number',
        ),
        migrations.AddField(
            model_name='landrequest',
            name='My_FarmerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
