# Generated by Django 3.0.3 on 2020-02-23 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0038_auto_20200222_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestequip',
            old_name='name',
            new_name='My_name',
        ),
        migrations.RemoveField(
            model_name='requestequip',
            name='receiver_id',
        ),
        migrations.RemoveField(
            model_name='requestequip',
            name='sender_ID',
        ),
        migrations.AddField(
            model_name='requestequip',
            name='My_FarmerID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipment',
            name='owners_id_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.AlterField(
            model_name='requestequip',
            name='equipment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.equipment'),
        ),
    ]
