# Generated by Django 3.0.3 on 2020-02-26 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0040_auto_20200223_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinaries',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.AlterField(
            model_name='veterinaries',
            name='ID_number',
            field=models.IntegerField(),
        ),
    ]
