# Generated by Django 3.0.3 on 2020-02-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0041_auto_20200226_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetrequest',
            old_name='Farmer_ID_number',
            new_name='FarmerID',
        ),
        migrations.RenameField(
            model_name='vetrequest',
            old_name='Veterinary_ID_number',
            new_name='Vet_ID',
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
