# Generated by Django 3.0.3 on 2020-02-27 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0044_auto_20200226_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='vetsession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPESA_code', models.IntegerField()),
                ('nationalID_number', models.IntegerField()),
                ('Vet_ID', models.IntegerField()),
                ('my_question', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
