# Generated by Django 3.0.3 on 2020-02-27 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0045_auto_20200227_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetsession',
            name='FarmerID',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.AlterField(
            model_name='vetsession',
            name='MPESA_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vetsession',
            name='Vet_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.veterinaries'),
        ),
    ]
