# Generated by Django 3.0.3 on 2020-02-27 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0047_auto_20200227_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.AlterField(
            model_name='vetsession',
            name='Vet_ID',
            field=models.IntegerField(),
        ),
    ]
