# Generated by Django 3.0.3 on 2020-02-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0049_auto_20200228_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='vetreply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FarmerID', models.IntegerField()),
                ('reply', models.TextField()),
            ],
        ),
    ]
