# Generated by Django 3.0.3 on 2020-02-28 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0050_vetreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetreply',
            name='Messsage_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Smallscale.vetsession'),
            preserve_default=False,
        ),
    ]
