# Generated by Django 3.0.3 on 2020-02-28 19:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0051_vetreply_messsage_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetreply',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vetrequest',
            name='Vet_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.veterinaries'),
        ),
        migrations.AlterField(
            model_name='vetsession',
            name='Vet_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.veterinaries'),
        ),
    ]
