# Generated by Django 3.0.3 on 2020-02-28 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0052_auto_20200228_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vetreply',
            old_name='Messsage_ID',
            new_name='Message_ID',
        ),
    ]
