# Generated by Django 3.0.3 on 2020-02-29 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0053_auto_20200228_2237'),
    ]

    operations = [
        migrations.AddField(
            model_name='landrequest',
            name='desired_lease_period',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='My_FarmerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
        migrations.AlterField(
            model_name='lands',
            name='farmerID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.Farmers'),
        ),
    ]
