# Generated by Django 3.0.3 on 2020-03-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0055_auto_20200229_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
        migrations.CreateModel(
            name='equiprentaL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MPESA_code', models.CharField(max_length=200)),
                ('payment_status', models.BooleanField(default=0)),
                ('request_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.requestequip')),
            ],
        ),
    ]
