# Generated by Django 3.0.3 on 2020-03-01 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0057_auto_20200301_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='equiprental',
            name='equipment_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Smallscale.equipment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
