# Generated by Django 3.0.3 on 2020-03-02 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0066_auto_20200302_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landrequest',
            name='My_name',
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
