# Generated by Django 3.0.3 on 2020-03-03 08:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Smallscale', '0072_auto_20200302_2341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equiprental',
            name='equipment_id',
        ),
        migrations.AddField(
            model_name='equiprental',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='landrequest',
            name='Land_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Smallscale.lands'),
        ),
    ]
